version: "3"

services:
  postgres: 
    container_name: postgres
    image: postgres:latest
    ports: 
    - "3000:3000"
    volumes:
    - /data:/data
    env_file:
    - docker.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge
